Use Kustomize to bundle MCAD CRDs
project-codeflare/codeflare-operator pull request #116
Opened 2023-05-31 13:50 UTC by astefanutti

This PR removes the manual sync of the MCAD CRDs, by pointing Kustomize to the source of truth directly.

It surfaces the dependency on MCAD, with a version that's currently hard-coded.

2023-05-31 14:04 UTC, astefanutti commented
/assign @anishasthana @sutaakar

2023-06-01 13:09 UTC, anishasthana requested changes

2023-06-02 08:25 UTC, astefanutti commented on config/crd/mcad/kustomization.yaml
> +  - github.com/astefanutti/multi-cluster-app-dispatcher/config/crd?ref=pr-01
I've just re-pushed it, as https://github.com/project-codeflare/multi-cluster-app-dispatcher/pull/401 is merged. It'll have to be changed once a new version of MCAD is released. That'll maybe be the opportunity to track the MCAD version that's depended on in a similar way as in #120.

2023-06-05 07:21 UTC, sutaakar approved these changes

2023-06-05 13:21 UTC, anishasthana approved these changes
/lgtm

2023-06-05 13:25 UTC, merged