Adjust rbac to match mcad
project-codeflare/codeflare-operator pull request #283
Opened 2023-09-12 06:05 UTC by jbusche

# Issue link
Closes https://github.com/project-codeflare/codeflare-operator/issues/187

# What changes have been made
Adjusts the mcad_controller.go rbac rules to match the recent changes with MCAD in PR https://github.com/project-codeflare/multi-cluster-app-dispatcher/pull/475

# Verification steps
Did a make image-build and deployed it, looked good.  

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x ] Manual tests
   - [ ] Testing is not required for this change
   
Checked the resulting rbac rules and they looked right. Left out the xqueuejobs as per @astefanutti suggestion.

2023-09-12 06:29 UTC, astefanutti commented
/lgtm

2023-09-12 06:33 UTC, astefanutti requested changes

2023-09-12 06:33 UTC, astefanutti commented on config/rbac/role.yaml
> +  - quota.codeflare.dev
This should also be added to the following manifest for the time being: https://github.com/project-codeflare/codeflare-operator/blob/2a4f5b8a6c5dc4dcf22be231999169eab87e08b7/config/internal/mcad/clusterrole_mcad-controller.yaml.tmpl#L14.

2023-09-12 20:07 UTC, jbusche commented
Testing looks good - clusterrole looks complete on my test system:
```
make image-build -e IMAGE_TAG_BASE=quay.io/jbusche/pr187 VERSION=rc5
make image-push -e IMAGE_TAG_BASE=quay.io/jbusche/pr187 VERSION=rc5
make deploy -e IMG=quay.io/jbusche/pr187:rc5
oc get clusterrole codeflare-operator-manager-role -o yaml
...
- apiGroups:
  - quota.codeflare.dev
  - workload.codeflare.dev
  resources:
  - appwrappers
  - appwrappers/finalizers
  - appwrappers/status
  - queuejobs
  - quotasubtrees
  - schedulingspecs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
```
And then the deploy of the codeflare kfdef looked good:
```
oc get pods |grep 136m
instascale-instascale-6bbccb5c8f-7xm9w                            1/1     Running   0          136m
kuberay-operator-b697b6d6d-shv7z                                  1/1     Running   0          136m
mcad-controller-mcad-89cbf885d-sfw8m                              1/1     Running   0          136m
```
And the guided sample deployed ok:
```
oc get pods -n default
NAME                                       READY   STATUS    RESTARTS   AGE
raytest-head-8pkk4                         1/1     Running   0          125m
raytest-worker-small-group-raytest-gthc2   1/1     Running   0          125m
raytest-worker-small-group-raytest-wgtz8   1/1     Running   0          125m
```

2023-09-13 08:52 UTC, sutaakar reviewed
/lgtm

2023-09-13 08:58 UTC, astefanutti commented
/approve

2023-09-13 09:01 UTC, merged