Update ocm-sdk dependency to address CVE
project-codeflare/codeflare-operator pull request #454
Opened 2024-01-26 12:26 UTC by Fiona-Waters

# Issue link
https://issues.redhat.com/browse/RHOAIENG-1311 

# What changes have been made
This PR will address a `Medium` level CVE:

**Introduced through**: golang.org/x/crypto@v0.14.0, golang.org/x/net@v0.17.0 and others.
**Fixed in**: golang.org/x/crypto@0.17.0

In order to update this indirect dependency I updated ocm-sdk-go dependency to v.0.1.393 which uses crypto v.0.17.0.

# Verification steps
E2E tests passing successfully will suffice.

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

2024-01-26 13:10 UTC, ChristianZaccaria requested changes
Usually, when an upgrade adds/removes a lot of dependencies (direct, indirect or transitive) it is best to verify that no new CVEs were introduced in the process.

I have Snyk setup in my own org to scan my own forked repositories on PRs made, for scenarios that include lots of changes.  I made a PR in my fork with this fix, which show that the CVE was effectively fixed, but a new one was introduced: https://github.com/ChristianZaccaria/codeflare-operator/pull/7 

I think we could look into `golang.org/x/net@v0.17.0` as it was also introduced through that one, perhaps changes are less involved there.

2024-01-26 17:16 UTC, ChristianZaccaria commented
/lgtm great work!

2024-01-26 17:16 UTC, ChristianZaccaria approved these changes
/lgtm great work!

2024-01-29 09:13 UTC, sutaakar approved these changes

2024-01-29 09:17 UTC, merged