Add new quickstart doc
project-codeflare/codeflare-operator pull request #552
Opened 2024-05-10 14:43 UTC by Ygnas

# Issue link

[RHOAIENG-6660](https://issues.redhat.com/browse/RHOAIENG-6660)
# What changes have been made

# Verification steps

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [x] Testing is not required for this change

Depends on #550

2024-05-10 15:07 UTC, Bobbins228 requested changes
I think this doc should be RHOAI leaning with ODH an alternate choice.
Also left a few nits 

Awesome work so far Ignas!

2024-05-10 15:07 UTC, Bobbins228 commented on Quick-Start.md
> +3. Search for and install the following operators:
We could specify here to install and that default settings are fine

2024-05-14 08:28 UTC, Fiona-Waters reviewed
Looks good. Just a few comments.

2024-05-14 08:28 UTC, Fiona-Waters commented on Quick-Start.md
> +cd codeflare-sdk
You could add a link here to instructions for installing codeflare sdk, maybe linking to the sdk [readme](https://github.com/project-codeflare/codeflare-sdk?tab=readme-ov-file#development) or add the instructions here
```suggestion
cd codeflare-sdk
pip install poetry
poetry install
```

2024-05-14 08:28 UTC, Fiona-Waters commented on Quick-Start.md
> +Post installation of the NVIDIA GPU Operator, proceed with creating a GPU ClusterPolicy Custom Resource (CR):
Nit pick
```suggestion
After installing the NVIDIA GPU Operator, proceed with creating a GPU ClusterPolicy Custom Resource (CR):
```

2024-05-14 08:28 UTC, Fiona-Waters commented on Quick-Start.md
> +2. Launch Jupyter Application:
Do we want users to create a data science project first? and launch the notebook from a workbench instead of bypassing this step

2024-05-14 08:28 UTC, Fiona-Waters commented on Quick-Start.md
> +## Red Hat OpenShift AI
I'm not sure if it is clear that this is an alternative to using `make all-in-one` rather than further instructions

2024-05-14 09:26 UTC, ChristianZaccaria requested changes
Looks great! Few nitpicks.

2024-05-14 09:26 UTC, ChristianZaccaria commented on Quick-Start.md
> +Get started with the guided demo notebooks for the CodeFlare-SDK by following these straightforward steps:
```suggestion
Get started with the guided demo notebooks for the CodeFlare-SDK by following these steps:
```

2024-05-15 08:26 UTC, Fiona-Waters reviewed
Changes look good. Just a couple more small things. Thanks Ignas.

2024-05-15 08:26 UTC, Fiona-Waters commented on Quick-Start.md
> +2. Look for tab labeled DSC Initialization.
I think that the DSCI is created while RHOAI is being installed and doesn't need to be created manually. Maybe double check this and have it as optional here - if it has not already been created.

2024-05-15 08:26 UTC, Fiona-Waters commented on Quick-Start.md
> +## Cleaning up the AI Platform Install
I think we should include both uninstallation scenarios - removal with delete-all-in-one and uninstallation through installed operators in openshift, just to be consistent.

2024-05-15 14:11 UTC, Fiona-Waters reviewed
/lgtm

2024-05-16 11:07 UTC, Fiona-Waters commented
Re-adding label after rebase.
/lgtm

2024-05-31 13:25 UTC, Fiona-Waters commented
/lgtm

2024-05-31 13:38 UTC, sutaakar commented
/lgtm

2024-05-31 14:41 UTC, sutaakar commented
/approve

2024-05-31 14:45 UTC, merged