Sync MCAD CRDS
project-codeflare/codeflare-operator pull request #89
Opened 2023-04-20 10:39 UTC by anishasthana

This PR introduces a make target to sync CRDS, in addition to syncing the CRDS.

2023-04-20 22:11 UTC, tedhtchang requested changes
The versions are still 0.0.1 in a few places.

2023-04-20 22:11 UTC, tedhtchang commented on bundle/manifests/codeflare-operator.clusterserviceversion.yaml
The CSV version still 0.0.1. Did you run `VERSION=0.0.2 make bundle`

2023-04-20 22:11 UTC, tedhtchang commented on config/manager/kustomization.yaml
> +  newTag: v0.0.1
v0.0.2

2023-04-20 22:11 UTC, tedhtchang commented on config/manifests/kustomization.yaml
> +- patch: '[{"op":"add", "path":"/metadata/annotations/containerImage", "value": "quay.io/project-codeflare/codeflare-operator:v0.0.1" }]'
v0.0.2

2023-05-01 17:59 UTC, jbusche approved these changes
LGTM, Tested on my OC 4.12.7 cluster using operator-sdk

2023-05-01 19:30 UTC, tedhtchang approved these changes
/approve

2023-05-01 19:30 UTC, tedhtchang commented on config/manifests/kustomization.yaml
> +    kind: ClusterServiceVersion
Hey @anishasthana Does this seem redundant ?

2023-05-01 19:30 UTC, tedhtchang commented on config/manifests/kustomization.yaml
> +    kind: ClusterServiceVersion
Doesn't seems to cause any problem

2023-05-01 19:35 UTC, merged